// <auto-generated />
using System;
using ItaasSolution.Api.Infraestructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItaasSolution.Api.Infraestructure.Migrations
{
    [DbContext(typeof(ItaasSolutionDbContext))]
    partial class ItaasSolutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ItaasSolution.Api.Domain.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CacheStatus")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DateCreation");

                    b.Property<string>("HtttpMethod")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ResponseSize");

                    b.Property<int>("StatusCode");

                    b.Property<decimal>("TimeTaken")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UriPath")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
